name: Build and Release

on:
  push:
    branches: ["main"]
    tags: ["v*"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "stable"

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Create Build Directory
        run: mkdir build

      - name: Build Packet (Go)
        run: |
          cd packet
          go build -o ../build/packet.exe .

      - name: Build XPlane UDP (Go)
        run: |
          cd xplane_udp
          go build -o ../build/XPlane_udp.exe ./src

      - name: Build SimConnect (C++)
        run: |
          msbuild SimConnect/SimConnect.vcxproj /p:Configuration=Release /p:Platform=x64 /p:OutDir=${{ github.workspace }}\build\

      - name: Build XPlane (C++)
        run: |
          msbuild XPlane/XPlane.vcxproj /p:Configuration=Release /p:Platform=x64 /p:OutDir=${{ github.workspace }}\build\temp_xplane\

      - name: Prepare XPlane Plugin Structure
        run: |
          mkdir build\OpenVolanta\win_64
          copy build\temp_xplane\OpenVolanta.xpl build\OpenVolanta\win_64\OpenVolanta.xpl

      - name: Create XPlane Plugin Zip
        shell: pwsh
        run: |
          Compress-Archive -Path build\OpenVolanta -DestinationPath build\OpenVolanta.zip

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: OpenVolanta-Build
          path: |
            build/packet.exe
            build/OpenVolanta.zip
            build/XPlane_udp.exe
            build/SimConnect.exe

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/packet.exe
            build/OpenVolanta.zip
            build/XPlane_udp.exe
            build/SimConnect.exe

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
